export const GET_TODOS = 'GET_TODOS';
export const GOT_TODOS = 'GOT_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const POST_TODO = 'POST_TODO';
export const DELETING_TODO = 'DELETING_TODO';
export const DELETING_TODOS = 'DELETING_TODOS';
export const DELETE_TODO = 'DELETE_TODO';
export const EDITING_TODO = 'EDITING_TODO';
export const TODO_UPDATED = 'TODO_UPDATED';
export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO';
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const ALL_TODOS_COMPLETED = 'ALL_TODOS_COMPLETED';
export const COMPLETED_CLEARED = 'COMPLETED_CLEARED';
export const COMPLETED_TODO = 'COMPLETED_TODO';